# Scene Configuration

scene_type: pile # options: piled 
# TODO: verify configuration setup for recreating ManipulationNet Scenes, Packed scenes, and Shelf scenes. use 'replica', 'packed' or 'shelf' respectively

# Scene name and prefix are overwritten in "../scripts/generatea_and_eval_scenes.sh" script. 
scene_name: "500"
scene_prefix: "batch1_"

# Object Parameters
object_set: moad # name of folder of objects_sets (objects_sets/<folder_name>)
num_objects: [4,7] # number of objects in a scene are randomly sampled from range provided
allow_duplicate_objects: True
list_of_objects: # specify grouping of objects to pick from
  - at1b1_bar-16mm
  - atb1_conn-dsub
  - atb1_conn-wp
  - atb1_gear-large
  - atb1_gear-medium
  - atb1_gear-small
  - atb1_nut-m16

# Boundary Parameters
boundary_shape: bin       # options: circle, bin
boundary_radius: [0.1, 0.3] # radius of boundary is randomly sampled from range provided
remove_boundary: True        # set False to keep containing bin throughout data collection. TODO: make sure that the multiple segments of the boundary act as a single unit instead of seperate objects. This will currently skew metrics results